In [1]:
import spacy
import pandas as pd
import numpy as np

import Modules.solrhandler as sh
import Modules.clusterer as cls
import Modules.topicdeterminator as td
import Modules.chatbot as cb

import warnings
warnings.filterwarnings(action='ignore')

In [2]:
#query = "anmeldung"
#target_service = 120686

In [3]:
# Import eval.csv
import os
file = os.path.realpath("../../Evaluierung/eval.csv")
eval = pd.read_csv(file, sep = ";")
eval = eval.head(20)
eval.head(20)

documentId                              file  dialogId  \
0       120697  20220131--quantEvalAllExcel.xlsx         4   
1       120686  20220131--quantEvalAllExcel.xlsx         4   
2       329421  20220131--quantEvalAllExcel.xlsx        19   
3       329421  20220131--quantEvalAllExcel.xlsx        19   
4       120914  20220131--quantEvalAllExcel.xlsx        23   
5       328200  20220131--quantEvalAllExcel.xlsx        24   
6       330073  20220131--quantEvalAllExcel.xlsx        28   
7       120702  20220131--quantEvalAllExcel.xlsx        36   
8       330150  20220131--quantEvalAllExcel.xlsx        39   
9       330174  20220131--quantEvalAllExcel.xlsx        47   
10      330118  20220131--quantEvalAllExcel.xlsx        48   
11      330118  20220131--quantEvalAllExcel.xlsx        48   
12      121151  20220131--quantEvalAllExcel.xlsx        58   
13      324328  20220131--quantEvalAllExcel.xlsx        73   
14      329421  20220131--quantEvalAllExcel.xlsx        79   
15      330118  20220131--quantEvalAllExcel.xlsx        83   
16      120726  20220131--quantEvalAllExcel.xlsx        93   
17      328137  20220131--quantEvalAllExcel.xlsx        94   
18      328137  20220131--quantEvalAllExcel.xlsx        94   
19      120926  20220131--quantEvalAllExcel.xlsx        98   

                                      initialQuestion  suggestionCount  \
0                                           Ummeldung                6   
1                                            Ummelden                6   
2   Pcr test positiv brauche ich eine Krankschreib...                6   
3                 Quarantäne Krankschreibung vom Arzt                6   
4                 Termin für Zulassung Gebrauchtwagen                6   
5   Wo kann ich mich nach Corona Infektion freites...                6   
6    Ab wann ist man bei Johnson & Johnson geboostert                5   
7                             Genesenen Bescheinigung                6   
8   welche medikamente kann man nehmen, wenn man c...                6   
9   ab 15.1. ist für Gäste von Restaurants  Nachwe...                6   
10  Ich habe mit einem Lateral-Flow-Test positiv g...                6   
11     wo kann ich einen kostenlosen PCR-Test machen?                6   
12                                   Termin Reisepass                6   
13           Ich benötige eine Fundbüro Bescheinigung                6   
14  Sehr geehrter Bobbi, wir haben fragen zum Sars...                6   
15                Wo ich kann schnell pcr test machen                6   
16  wir haben vor wenigen Tagen eine Anzeige erste...                6   
17                                                  C                4   
18                               Symptome der Impfung                5   
19                                    Führungszeugnis                4   

    directlyFound                                               name  
0            True                  Änderung/Wechsel der Hauptwohnung  
1            True                            Anmeldung einer Wohnung  
2           False  Erstattung nach Infektionsschutzgesetz bei Tät...  
3            True  Erstattung nach Infektionsschutzgesetz bei Tät...  
4            True  Zulassung eines Fahrzeuges mit auswärtigem Ken...  
5            True  Infektionskrankheiten melden - für Gemeinschaf...  
6            True                 Impfung gegen Corona (SARS-CoV-2)   
7            True                      Meldebescheinigung beantragen  
8            True  Arzneimittel - zur Sachkundeprüfung für den Ha...  
9            True  Gaststättengewerbe - zum Unterrichtungsnachwei...  
10          False     Coronavirus - Beschaffung von Tests beantragen  
11           True     Coronavirus - Beschaffung von Tests beantragen  
12           True                               Reisepass beantragen  
13           True       Fundsachen - Verlorene Sachen zurückbekommen  
14           True  Erstattung nach Infektionsschutzgesetz bei Tät...  
15        

In [4]:
#eval.iloc[2]["initialQuestion"]

Funktionen

In [5]:
def findCorrectAnswer(chatbot,targetService):

    # Find Target Cluster
    clusteredColumn = chatbot.clusterer.getClusteredColumn()
    service = chatbot.df.loc[chatbot.df["id"]==str(targetService)]
    if len(service[clusteredColumn].values) == 0:
        return None

    targetCluster = service[clusteredColumn].values[0]

    if targetCluster == chatbot.getSelectedClusterForQuestion():
        return True

    else:
        return False

def getRank(chatbot, targetService):
    temp = chatbot.df.reset_index()
    try:
        rank = temp.index[temp["id"]==str(targetService)].values[0]
    except IndexError as e:
        return float("NaN")
    return rank + 1

Logging

In [6]:
class Logger:
    
    def __init__(self, eval_df):
        self.liste = []
        self.eval_df = eval_df
        self.chatbot = None
    
    def getDataFrame(self): # TODO
        pass
    
    def setChatbot(self, chatbot):
        self.chatbot = chatbot
    
    def log(self, ID, t, row, answer = None, initialQuery = False): 
        target_service = row["documentId"]
        
        dialogId = row["dialogId"]
        file = row["file"]
        
        service_name = row["name"]
        query = row["initialQuestion"]
        
        if initialQuery:
            nResults = len(self.chatbot.df.index)
            rank = getRank(self.chatbot,target_service)# getRank(target_service)

            row = (file, dialogId, ID, t, service_name, query, "initialQuery", None, rank, nResults)
        else:
            if answer is not None:


                nResults = len(self.chatbot.df.index)
                question = self.chatbot.generateQuestion()
                answer = answer

                rank = getRank(self.chatbot,target_service)# getRank(target_service)

                row = (file, dialogId, ID, t,  service_name, query, question, answer, rank, nResults)
            else:
                row = (file, dialogId, ID, t, service_name, query, None, None, None, None)
        self.liste.append(row)
        #print(self.liste)

TEST

Execution

In [7]:
# Initialisierung Komponenten Chatbot
#solrhandler = sh.SolrHandler(1000)
#clusterer = cls.Clusterer()
#tpc_dterminator = td.TopicDeterminator()

from sklearn.cluster import DBSCAN


In [8]:
# Experiment durchlaufen und Loggen
lg = Logger(eval_df = eval)   

for (ID, row) in eval.iterrows():
    #print(ID)
    
    query = row["initialQuestion"]
    target_service = row["documentId"]
    t = 0
    
    # Chatbot initialisieren
    try: # 1.3
        chatbot = cb.Chatbot(query,3,sh.SolrHandler(2000),cls.Clusterer(clustering_algorithm = DBSCAN(eps=1.3, min_samples=1)),td.TopicDeterminator(), forceClusters = True)
    
    # Fehler überspringen: eg. kein solr output
    except Exception as e: 
        if(str(e) == 'response'): # TODO ??
            next
        elif(str(e) == 'no solr output'):
            next
        else:
            print(e)
            
    lg.setChatbot(chatbot)

    
    answer = findCorrectAnswer(chatbot, target_service)
    
    if answer is None: # service nicht in resultset, überspringen
        next
    lg.log(ID,t, row, answer, initialQuery = True)
    
    while not chatbot.isFinished():#chatbot.refineResultset(answer, recluster = True):

        # log
        t += 1
        
        print(ID)
        print(t)
        print(np.unique(chatbot.df["ssdsLemma_cluster"]))
        print("")
        
        chatbot.refineResultset(answer)
        answer = findCorrectAnswer(chatbot, target_service)
        if answer is None: 
            break
        lg.log(ID, t, row,answer)
        
        #print(chatbot.clusterer.clustering_algorithm.eps)

0
1
[0 1 2]

0
2
[0 1 2 3]

1
1
[0 1 2]

2
1
[0 1 2 3 4]

2
2
[0 1 2 3]

3
1
[0 1 2]

4
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

4
2
[0 1]

4
3
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]

4
4
[0 1]

4
5
[0 1 2 3 4 5]

4
6
[0 1 2 3 4 5]

7
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32]

7
2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]

7
3
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]

7
4
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

7
5
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28]

7
6
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]

7
7
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 2

In [9]:
log_df = pd.DataFrame(lg.liste, columns=["file","dialogId", "ID","t", "name", "query", "question", "answer", "rank", "nResult"])
#log_df.head(40)

Log Analyzer - Jannis

In [10]:
import Modules.log_analyzer as lo_an

In [11]:
log_analyzer = lo_an.Log_Analyzer(log_df)
#delta, services, questions, means = log_analyzer.run_it()
results = log_analyzer.run_it()

In [12]:
log_df.head(40)

file  dialogId  ID  t  \
0   20220131--quantEvalAllExcel.xlsx         4   0  0   
1   20220131--quantEvalAllExcel.xlsx         4   0  1   
2   20220131--quantEvalAllExcel.xlsx         4   0  2   
3   20220131--quantEvalAllExcel.xlsx         4   1  0   
4   20220131--quantEvalAllExcel.xlsx        19   2  0   
5   20220131--quantEvalAllExcel.xlsx        19   2  1   
6   20220131--quantEvalAllExcel.xlsx        19   2  2   
7   20220131--quantEvalAllExcel.xlsx        19   3  0   
8   20220131--quantEvalAllExcel.xlsx        19   3  1   
9   20220131--quantEvalAllExcel.xlsx        23   4  0   
10  20220131--quantEvalAllExcel.xlsx        23   4  1   
11  20220131--quantEvalAllExcel.xlsx        23   4  2   
12  20220131--quantEvalAllExcel.xlsx        23   4  3   
13  20220131--quantEvalAllExcel.xlsx        23   4  4   
14  20220131--quantEvalAllExcel.xlsx        23   4  5   
15  20220131--quantEvalAllExcel.xlsx        23   4  6   
16  20220131--quantEvalAllExcel.xlsx        24   5  0   
17  20220131--quantEvalAllExcel.xlsx        28   6  0   
18  20220131--quantEvalAllExcel.xlsx        36   7  0   
19  20220131--quantEvalAllExcel.xlsx        36   7  1   
20  20220131--quantEvalAllExcel.xlsx        36   7  2   
21  20220131--quantEvalAllExcel.xlsx        36   7  3   
22  20220131--quantEvalAllExcel.xlsx        36   7  4   
23  20220131--quantEvalAllExcel.xlsx        36   7  5   
24  20220131--quantEvalAllExcel.xlsx        36   7  6   
25  20220131--quantEvalAllExcel.xlsx        36   7  7   
26  20220131--quantEvalAllExcel.xlsx        36   7  8   
27  20220131--quantEvalAllExcel.xlsx        36   7  9   
28  20220131--quantEvalAllExcel.xlsx        39   8  0   
29  20220131--quantEvalAllExcel.xlsx        47   9  0   
30  20220131--quantEvalAllExcel.xlsx        47   9  1   
31  20220131--quantEvalAllExcel.xlsx        47   9  2   
32  20220131--quantEvalAllExcel.xlsx        47   9  3   
33  20220131--quantEvalAllExcel.xlsx        47   9  4   
34  20220131--quantEvalAllExcel.xlsx        48  10  0   
35  20220131--quantEvalAllExcel.xlsx        48  11  0   
36  20220131--quantEvalAllExcel.xlsx        58  12  0   
37  20220131--quantEvalAllExcel.xlsx        58  12  1   
38  20220131--quantEvalAllExcel.xlsx        58  12  2   
39  20220131--quantEvalAllExcel.xlsx        73  13  0   

                                                 name  \
0                   Änderung/Wechsel der Hauptwohnung   
1                   Änderung/Wechsel der Hauptwohnung   
2                   Änderung/Wechsel der Hauptwohnung   
3                             Anmeldung einer Wohnung   
4   Erstattung nach Infektionsschutzgesetz bei Tät...   
5   Erstattung nach Infektionsschutzgesetz bei Tät...   
6   Erstattung nach Infektionsschutzgesetz bei Tät...   
7   Erstattung nach Infektionsschutzgesetz bei Tät...   
8   Erstattung nach Infektionsschutzgesetz bei Tät...   
9   Zulassung eines Fahrzeuges mit auswärtigem Ken...   
10  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
11  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
12  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
13  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
14  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
15  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
16  Infektionskrankheiten melden - für Gemeinschaf...   
17                 Impfung gegen Corona (SARS-CoV-2)    
18                      Meldebescheinigung beantragen   
19                      Meldebescheinigung beantragen   
20                      Meldebescheinigung beantragen   
21                      Meldebescheinigung beantragen   
22                      Meldebescheinigung beantragen   
23                      Meldebescheinigung beantragen   
24                      Meldebescheinigung beantragen   
25                      Meldebescheinigung beantragen   
26                      Meldebescheinigung beantragen   
27                      Meldebescheinigung beantragen   
28  Arzneimittel - zur Sachkundeprüfung f

In [13]:
len(results)

5

In [14]:
results[0]

file  dialogId  ID  t  \
0   20220131--quantEvalAllExcel.xlsx         4   0  0   
1   20220131--quantEvalAllExcel.xlsx         4   0  1   
2   20220131--quantEvalAllExcel.xlsx         4   0  2   
3   20220131--quantEvalAllExcel.xlsx         4   1  0   
4   20220131--quantEvalAllExcel.xlsx        19   2  0   
5   20220131--quantEvalAllExcel.xlsx        19   2  1   
6   20220131--quantEvalAllExcel.xlsx        19   2  2   
7   20220131--quantEvalAllExcel.xlsx        19   3  0   
8   20220131--quantEvalAllExcel.xlsx        19   3  1   
9   20220131--quantEvalAllExcel.xlsx        23   4  0   
10  20220131--quantEvalAllExcel.xlsx        23   4  1   
11  20220131--quantEvalAllExcel.xlsx        23   4  2   
12  20220131--quantEvalAllExcel.xlsx        23   4  3   
13  20220131--quantEvalAllExcel.xlsx        23   4  4   
14  20220131--quantEvalAllExcel.xlsx        23   4  5   
15  20220131--quantEvalAllExcel.xlsx        23   4  6   
16  20220131--quantEvalAllExcel.xlsx        24   5  0   
17  20220131--quantEvalAllExcel.xlsx        28   6  0   
18  20220131--quantEvalAllExcel.xlsx        36   7  0   
19  20220131--quantEvalAllExcel.xlsx        36   7  1   
20  20220131--quantEvalAllExcel.xlsx        36   7  2   
21  20220131--quantEvalAllExcel.xlsx        36   7  3   
22  20220131--quantEvalAllExcel.xlsx        36   7  4   
23  20220131--quantEvalAllExcel.xlsx        36   7  5   
24  20220131--quantEvalAllExcel.xlsx        36   7  6   
25  20220131--quantEvalAllExcel.xlsx        36   7  7   
26  20220131--quantEvalAllExcel.xlsx        36   7  8   
27  20220131--quantEvalAllExcel.xlsx        36   7  9   
28  20220131--quantEvalAllExcel.xlsx        39   8  0   
29  20220131--quantEvalAllExcel.xlsx        47   9  0   
30  20220131--quantEvalAllExcel.xlsx        47   9  1   
31  20220131--quantEvalAllExcel.xlsx        47   9  2   
32  20220131--quantEvalAllExcel.xlsx        47   9  3   
33  20220131--quantEvalAllExcel.xlsx        47   9  4   
34  20220131--quantEvalAllExcel.xlsx        48  10  0   
35  20220131--quantEvalAllExcel.xlsx        48  11  0   
36  20220131--quantEvalAllExcel.xlsx        58  12  0   
37  20220131--quantEvalAllExcel.xlsx        58  12  1   
38  20220131--quantEvalAllExcel.xlsx        58  12  2   
39  20220131--quantEvalAllExcel.xlsx        73  13  0   
40  20220131--quantEvalAllExcel.xlsx        73  13  1   
41  20220131--quantEvalAllExcel.xlsx        73  13  2   
42  20220131--quantEvalAllExcel.xlsx        73  13  3   
43  20220131--quantEvalAllExcel.xlsx        73  13  4   
44  20220131--quantEvalAllExcel.xlsx        73  13  5   
45  20220131--quantEvalAllExcel.xlsx        73  13  6   
46  20220131--quantEvalAllExcel.xlsx        79  14  0   
47  20220131--quantEvalAllExcel.xlsx        83  15  0   
48  20220131--quantEvalAllExcel.xlsx        93  16  0   
49  20220131--quantEvalAllExcel.xlsx        93  16  1   
50  20220131--quantEvalAllExcel.xlsx        93  16  2   
51  20220131--quantEvalAllExcel.xlsx        93  16  3   
52  20220131--quantEvalAllExcel.xlsx        94  17  0   
53  20220131--quantEvalAllExcel.xlsx        94  18  0   
54  20220131--quantEvalAllExcel.xlsx        94  18  1   
55  20220131--quantEvalAllExcel.xlsx        98  19  0   

                                                 name  \
0                   Änderung/Wechsel der Hauptwohnung   
1                   Änderung/Wechsel der Hauptwohnung   
2                   Änderung/Wechsel der Hauptwohnung   
3                             Anmeldung einer Wohnung   
4   Erstattung nach Infektionsschutzgesetz bei Tät...   
5   Erstattung nach Infektionsschutzgesetz bei Tät...   
6   Erstattung nach Infektionsschutzgesetz bei Tät...   
7   Erstattung nach Infektionsschutzgesetz bei Tät...   
8   Erstattung nach Infektionsschutzgesetz bei Tät...   
9   Zulassung eines Fahrzeuges mit auswärtigem Ken...   
10  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
11  Zulassung eines Fahrzeuges mit auswärtigem Ken...   
12  Zulassung eines Fahrzeuges mit auswär

Statistics ( Alt)

In [15]:
# avg Rank Improvement in turn t
log_df["delta_Rank"] = log_df.groupby(["ID"])["rank"].diff()
#log_df.groupby(["t"])["rank_improvement"].mean()

In [17]:
# avg nSuggestions Improvement in turn t
log_df["delta_nResult"] = log_df.groupby(["ID"])["nResult"].diff()
#log_df.groupby(["t"])["sugg_improvement"].mean()

In [ ]:
# MRR ohne cluster refinement
#df = log_df.loc[log_df["t"] == 1]
#MRR_ohne = 1/(df["rank"].mean())
#MRR_ohne

In [ ]:
# MRR mit cluster refinement
#df = log_df.groupby(["ID"]).last("t")
#MRR_mit = 1/(df["rank"].mean())
#MRR_mit
#df.head()

In [19]:
# avg Turns
print(log_df["t"].mean())

# bei durchschnittlich nResults
print(log_df.groupby(["ID"]).last("t")["nResult"].mean())

2.0357142857142856
2.05


In [ ]:
log_df.head(20)